version: "3.8"
services:
  server:
    build: .
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mysqldb
  mysqldb:
    platform: linux/amd64
    image: "mysql:5.7"
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: demogk
      MYSQL_USER: sangnguyen
      MYSQL_PASSWORD: Sanghb57@
      MYSQL_ROOT_PASSWORD: Sanghb57@